### ISSUE TITLE
Cannot find release

### ISSUE THREAD

**Issue by Suyashtnt** [sd2k/grafana-tokio-console-datasource#13]
I am unable to find a release on the plugin website. Are you sure it is there?

**Comment by sd2k** [comment]
Hi! Sorry about this, it took a while for the plugin to go through the review process. It's now available at https://grafana.com/grafana/plugins/bsull-console-datasource/, but currently only works with Grafana 8.4 - I need to issue a new release (and wait for review) for it to work with Grafana 9.
